version: 0.0
os: linux
files:
  - source: app.jar
    destination: /home/ec2-user/app
  - source: scripts/
    destination: /home/ec2-user/app/scripts/
hooks:

  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 180
      runas: ec2-user

