apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: 961581626265.dkr.ecr.ap-south-1.amazonaws.com/banking-app:latest
          ports:
            - containerPort: 8080

